name: video_app_flutter
description: A new flutter module project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Features
  home:
    path: features/home
  in_video_content:
    path: features/in_video_content

  # Domains
  video:
    path: domains/video

  # Resources
  resources:
    path: resources/resources

  # Shared libraries
  common:
    path: shared_libraries/common
  component:
    path: shared_libraries/component
  core:
    path: shared_libraries/core
  dependencies:
    path: shared_libraries/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.video_app.video_app_flutter
    iosBundleIdentifier: com.videoapp.videoAppFlutter
